### PR TITLE
Added boolean for whether queries are running

### PR DESCRIPTION
**Pull request by dylanratcliffe**

### CODE REVIEW

**Comment by dylanratcliffe** [comment]
@getinnocuous This is the boolean that we discussed, you should be able to use this to determine if we should show the spinner or not

**Comment by getinnocuous** [comment]
How does this get consumed? Does it require a call each time to get the value?

**Comment by dylanratcliffe** [comment]
Given its a getter I'm not 100% sure how react will handle it. I'm hoping you can just bind `session.queriesRunning` to the UI and that's it, but it'll require testing

**Comment by dylanratcliffe** [comment]
Hopefully it's smart enough to see the underlying value change and then change detection can handle it. If it doesn't work we can always do another event handler

**Comment by dylanratcliffe** [comment]
Closing in favour of implementing it as an event listener in React

**Pull request closed without merging**
